name: build & publish docker image
on: push

jobs:
   build:
      runs-on: ubuntu-latest
      steps:
      
      - name: Code Checkout
        uses: actions/checkout@v4.1.5

      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
           username: ${{ secrets.USERNAME }}
           password: ${{ secrets.PASSWORD }}

      - name: Build Image
        run: | 
          docker build -t rennieg:v1 .
          docker tag rennieg:v1 sammielas/rennieg:v1
          docker push sammielas/rennieg:v1
